### ISSUE TITLE
Creation d'un modele : Champs / bouton manquants 

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/datainjection#132]
Bonjour,

GLPI 9.3.1

Sous chrome ou IE : 
2.61 et 2.63 : Creation d'un modele : 
![image](https://user-images.githubusercontent.com/42341169/47091056-67fba200-d224-11e8-83b8-66eec014d1a1.png)

Il manque des champs : pas de bouton ? rien ?

D'avance merci

**Comment by cedric-anne** [comment]
Hi,

Can you check in your log files if there is any error ?

Regards

**Comment by EC2311** [comment]
In php error log : 
[2018-10-18 11:49:18] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in ...\inc\toolbox.class.php line 657
  *** PHP Warning(2): Declaration of PluginAppliancesApplianceInjection::getTable() should be compatible with CommonDBTM::getTable($classname = NULL)
  Backtrace :
  ...\appliances\inc\applianceinjection.class.php:39 
  inc\autoload.function.php:368                      include_once()
  :                                                  glpi_autoload()
  ...ns\datainjection\inc\injectiontype.class.php:52 spl_autoload_call()
  ...ns\datainjection\inc\injectiontype.class.php:89 PluginDatainjectionInjectionType::getItemtypes()
  plugins\datainjection\inc\model.class.php:662      PluginDatainjectionInjectionType::dropdown()
  plugins\datainjection\inc\model.class.php:590      PluginDatainjectionModel->showAdvancedForm()
  inc\commonglpi.class.php:478                       PluginDatainjectionModel->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2018-10-18 11:49:22] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in ...\inc\toolbox.class.php line 657
  *** PHP Warning(2): Declaration of PluginAppliancesApplianceInjection::getTable() should be compatible with CommonDBTM::getTable($classname = NULL)
  Backtrace :
  ...\appliances\inc\applianceinjection.class.php:39 
  inc\autoload.function.php:368                      include_once()
  :                                                  glpi_autoload()
  ...ns\datainjection\inc\injectiontype.class.php:52 spl_autoload_call()
  ...ns\datainjection\inc\injectiontype.class.php:89 PluginDatainjectionInjectionType::getItemtypes()
  plugins\datainjection\inc\model.class.php:662      PluginDatainjectionInjectionType::dropdown()
  plugins\datainjection\inc\model.class.php:590      PluginDatainjectionModel->showAdvancedForm()
  inc\commonglpi.class.php:478                       PluginDatainjectionModel->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
 
In ajax debug Mode : 
Fatal error: Uncaught Error: Class 'PluginDataflowsDataflowInjection' not found in ...\plugins\datainjection\inc\injectiontype.class.php:52 Stack trace: #0 ...\plugins\datainjection\inc\injectiontype.class.php(89): PluginDatainjectionInjectionType::getItemtypes(true) #1 ...\plugins\datainjection\inc\model.class.php(662): PluginDatainjectionInjectionType::dropdown('', true) #2 ...\plugins\datainjection\inc\model.class.php(590): PluginDatainjectionModel->showAdvancedForm('') #3 ...\inc\commonglpi.class.php(478): PluginDatainjectionModel->showForm('', Array) #4 ...\ajax\common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginDatainjectionModel), 'PluginDatainjec...', '', Array) #5 {main} thrown in ...\plugins\datainjection\inc\injectiontype.class.php on line 52

**Comment by cedric-anne** [comment]
Looks like there is an error with `Dataflows` plugin. Could you disable it and check if it works better ?
